In [1]:
import pandas as pd

In [2]:
pos = pd.read_csv("D:/AI/HomeCredit/Dataset/POS_CASH_balance.csv")

In [3]:
pos_agg_prev = pos.groupby('SK_ID_PREV').agg(
    pos_months_count = ('MONTHS_BALANCE', 'count'),
    pos_months_min = ('MONTHS_BALANCE', 'min'),
    pos_months_max = ('MONTHS_BALANCE', 'max'),
    pos_cnt_instalment_mean = ('CNT_INSTALMENT', 'mean'),
    pos_cnt_instalment_future_mean = ('CNT_INSTALMENT_FUTURE', 'mean'),
    pos_dpd_max = ('SK_DPD', 'max'),
    pos_dpd_mean = ('SK_DPD', 'mean'),
    pos_dpd_def_max = ('SK_DPD_DEF', 'max'),
    pos_overdue_months = ('SK_DPD', lambda x: (x>0).sum()),
    pos_severe_overdue_months = ('SK_DPD_DEF', lambda x: (x>0).sum())
).reset_index()

In [4]:
pos = pd.get_dummies(
    pos,
    columns=['NAME_CONTRACT_STATUS'],
    prefix='POS_STATUS',
    dummy_na=False
)
pos_final = pos.merge(pos_agg_prev, on='SK_ID_PREV', how='left')
pos_final = pos_final.groupby('SK_ID_CURR').agg(['mean', 'sum', 'max'])
pos_final.columns = ['_'.join(col).upper() for col in pos_final.columns]
pos_final.reset_index(inplace=True)
pos_final

,SK_ID_CURR,SK_ID_PREV_MEAN,SK_ID_PREV_SUM,SK_ID_PREV_MAX,MONTHS_BALANCE_MEAN,MONTHS_BALANCE_SUM,MONTHS_BALANCE_MAX,CNT_INSTALMENT_MEAN,CNT_INSTALMENT_SUM,CNT_INSTALMENT_MAX,...,POS_DPD_MEAN_MAX,POS_DPD_DEF_MAX_MEAN,POS_DPD_DEF_MAX_SUM,POS_DPD_DEF_MAX_MAX,POS_OVERDUE_MONTHS_MEAN,POS_OVERDUE_MONTHS_SUM,POS_OVERDUE_MONTHS_MAX,POS_SEVERE_OVERDUE_MONTHS_MEAN,POS_SEVERE_OVERDUE_MONTHS_SUM,POS_SEVERE_OVERDUE_MONTHS_MAX
0,100001,1.584045e+06,14256401,1851984,-72.555556,-653,-53,4.000000,36.0,4.0,...,1.750000,3.111111,28,7,0.444444,4,1,0.444444,4,1
1,100002,1.038818e+06,19737542,1038818,-10.000000,-190,-1,24.000000,456.0,24.0,...,0.000000,0.000000,0,0,0.000000,0,0,0.000000,0,0
2,100003,2.297665e+06,64334628,2636178,-43.785714,-1226,-18,10.107143,283.0,12.0,...,0.000000,0.000000,0,0,0.000000,0,0,0.000000,0,0
3,100004,1.564014e+06,6256056,1564014,-25.500000,-102,-24,3.750000,15.0,4.0,...,0.000000,0.000000,0,0,0.000000,0,0,0.000000,0,0
4,100005,2.495675e+06,27452425,2495675,-20.000000,-220,-15,11.700000,117.0,12.0,...,0.000000,0.000000,0,0,0.000000,0,0,0.000000,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
337247,456251,2.248017e+06,20232153,2248017,-5.000000,-45,-1,7.875000,63.0,8.0,...,0.000000,0.000000,0,0,0.000000,0,0,0.000000,0,0
337248,456252,1.503599e+06,10525193,1503599,-79.000000,-553,-76,6.000000,42.0,6.0,...,0.000000,0.000000,0,0,0.000000,0,0,0.000000,0,0
337249,456253,1.760593e+06,29930087,2029307,-79.235294,-1347,-57,6.705882,114.0,12.0,...,0.833333,1.764706,30,5,0.352941,6,1,0.352941,6,1
337250,456254,1.893484e+06,37869673,2016407,-5.550000,-111,-1,14.900000,298.0,16.0,...,0.000000,0.000000,0,0,0.000000,0,0,0.000000,0,0
337251,456255,1.951191e+06,138534533,2729207,-16.408451,-1165,-2,22.788732,1618.0,36.0,...,0.454545,0.774648,55,5,0.154930,11,1,0.154930,11,1

In [5]:
inst = pd.read_csv("D:/AI/HomeCredit/Dataset/installments_payments.csv")

In [6]:
inst['PAYMENT_DELAY'] = inst['DAYS_ENTRY_PAYMENT'] - inst['DAYS_INSTALMENT']
inst['PAYMENT_DIFF'] = inst['AMT_INSTALMENT'] - inst['AMT_PAYMENT']
inst['PAYMENT_RATIO'] = inst['AMT_PAYMENT'] / (inst['AMT_INSTALMENT'] + 1e-6)

In [7]:
inst_agg_prev = inst.groupby('SK_ID_PREV').agg(
    inst_count = ('NUM_INSTALMENT_NUMBER', 'count'),
    payment_delay_mean = ('PAYMENT_DELAY', 'mean'),
    payment_delay_max = ('PAYMENT_DELAY', 'max'),
    payment_ratio_mean = ('PAYMENT_RATIO', 'mean'),
    payment_ratio_min = ('PAYMENT_RATIO', 'min'),
    payment_diff_sum = ('PAYMENT_DIFF', 'sum'),
    late_payments = ('PAYMENT_DELAY', lambda x: (x>0).sum())
).reset_index()

In [14]:
inst_final = inst.merge(inst_agg_prev, on='SK_ID_PREV', how='left')
inst_final = inst_final.groupby('SK_ID_CURR').agg(['mean','sum','max'])
inst_final.columns = ['_'.join(col).upper() for col in inst_final.columns]
inst_final.reset_index()

,SK_ID_CURR,SK_ID_PREV_MEAN,SK_ID_PREV_SUM,SK_ID_PREV_MAX,NUM_INSTALMENT_VERSION_MEAN,NUM_INSTALMENT_VERSION_SUM,NUM_INSTALMENT_VERSION_MAX,NUM_INSTALMENT_NUMBER_MEAN,NUM_INSTALMENT_NUMBER_SUM,NUM_INSTALMENT_NUMBER_MAX,...,PAYMENT_RATIO_MEAN_MAX,PAYMENT_RATIO_MIN_MEAN,PAYMENT_RATIO_MIN_SUM,PAYMENT_RATIO_MIN_MAX,PAYMENT_DIFF_SUM_MEAN,PAYMENT_DIFF_SUM_SUM,PAYMENT_DIFF_SUM_MAX,LATE_PAYMENTS_MEAN,LATE_PAYMENTS_SUM,LATE_PAYMENTS_MAX
0,100002,1.038818e+06,8310544,1038818,1.125000,9,2,13.500000,108,19,...,1.000000,1.000000,8.000000,1.000000,0.0000,0.000,0.000,0.000000,0,0
1,100003,2.201343e+06,13208056,2396755,1.000000,6,1,5.000000,30,9,...,1.000000,1.000000,6.000000,1.000000,0.0000,0.000,0.000,0.000000,0,0
2,100005,2.495675e+06,7487025,2495675,1.333333,4,2,4.666667,14,9,...,1.000000,1.000000,3.000000,1.000000,0.0000,0.000,0.000,0.000000,0,0
3,100006,2.207992e+06,13247949,2299329,1.333333,8,2,4.166667,25,7,...,1.000000,1.000000,6.000000,1.000000,0.0000,0.000,0.000,0.000000,0,0
4,100007,2.081470e+06,22896170,2462742,1.000000,11,1,5.454545,60,11,...,1.000000,1.000000,11.000000,1.000000,0.0000,0.000,0.000,0.363636,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92329,199994,2.354138e+06,2354138,2354138,1.000000,1,1,3.000000,3,3,...,1.000000,1.000000,1.000000,1.000000,0.0000,0.000,0.000,0.000000,0,0
92330,199995,2.126495e+06,6379485,2126495,1.333333,4,2,3.666667,11,6,...,0.999568,0.998705,2.996115,0.998705,13.0500,39.150,13.050,1.000000,3,1
92331,199997,1.507496e+06,9044973,1819884,1.000000,6,1,7.000000,42,15,...,1.000000,1.000000,6.000000,1.000000,0.0000,0.000,0.000,0.000000,0,0
92332,199998,2.237050e+06,89481981,2831310,0.725000,29,3,17.225000,689,72,...,1.000000,0.727190,29.087613,1.000000,10206.3240,408252.960,38074.410,0.775000,31,2
92333,199999,1.498454e+06,37461361,2268653,1.000000,25,1,7.440000,186,23,...,1.000000,0.999802,24.995048,1.000000,1.8702,46.755,46.755,0.040000,1,1

In [9]:
cc = pd.read_csv("D:/AI/HomeCredit/Dataset/credit_card_balance.csv")
cc.head()

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,...,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,2562384,378907,-6,56.970,135000,0.0,877.5,0.0,877.5,1700.325,...,0.000,0.000,0.0,1,0.0,1.0,35.0,Active,0,0
1,2582071,363914,-1,63975.555,45000,2250.0,2250.0,0.0,0.0,2250.000,...,64875.555,64875.555,1.0,1,0.0,0.0,69.0,Active,0,0
2,1740877,371185,-7,31815.225,450000,0.0,0.0,0.0,0.0,2250.000,...,31460.085,31460.085,0.0,0,0.0,0.0,30.0,Active,0,0
3,1389973,337855,-4,236572.110,225000,2250.0,2250.0,0.0,0.0,11795.760,...,233048.970,233048.970,1.0,1,0.0,0.0,10.0,Active,0,0
4,1891521,126868,-1,453919.455,450000,0.0,11547.0,0.0,11547.0,22924.890,...,453919.455,453919.455,0.0,1,0.0,1.0,101.0,Active,0,0

In [11]:
cc['UTILIZATION'] = cc['AMT_BALANCE'] / cc['AMT_CREDIT_LIMIT_ACTUAL']
cc['PAYMENT_RATIO'] = cc['AMT_PAYMENT_TOTAL_CURRENT'] / cc['AMT_TOTAL_RECEIVABLE']

In [13]:
cc_agg_prev = cc.groupby('SK_ID_PREV').agg(
    cc_months_count = ('MONTHS_BALANCE','count'),
    utilization_mean = ('UTILIZATION', 'mean'),
    utilization_max = ('UTILIZATION', 'max'),
    payment_ratio_mean = ('PAYMENT_RATIO', 'mean'),
    cc_dpd_max = ('SK_DPD', 'max'),
    cc_dpd_def_max = ('SK_DPD_DEF', 'max'),
    total_drawings = ('AMT_DRAWINGS_CURRENT' , 'sum')
).reset_index()

In [16]:
cc_final = cc.merge(cc_agg_prev , on ='SK_ID_PREV', how = 'left')
num_cols = cc_final.select_dtypes(include=['int64','float64']).columns
cc_final = cc_final.groupby('SK_ID_CURR')[num_cols]. agg(['mean','sum','max'])
cc_final.columns = ['_'.join(col).upper()for col in cc_final.columns]
cc_final.reset_index(inplace=True)

In [17]:
cc_final.head()

,SK_ID_CURR,SK_ID_PREV_MEAN,SK_ID_PREV_SUM,SK_ID_PREV_MAX,SK_ID_CURR_MEAN,SK_ID_CURR_SUM,SK_ID_CURR_MAX,MONTHS_BALANCE_MEAN,MONTHS_BALANCE_SUM,MONTHS_BALANCE_MAX,...,PAYMENT_RATIO_MEAN_MAX,CC_DPD_MAX_MEAN,CC_DPD_MAX_SUM,CC_DPD_MAX_MAX,CC_DPD_DEF_MAX_MEAN,CC_DPD_DEF_MAX_SUM,CC_DPD_DEF_MAX_MAX,TOTAL_DRAWINGS_MEAN,TOTAL_DRAWINGS_SUM,TOTAL_DRAWINGS_MAX
0,100006,1489396.0,8936376,1489396,100006.0,600036,100006,-3.5,-21,-1,...,NaN,0.0,0,0,0.0,0,0,0.0,0.0,0.0
1,100011,1843384.0,136410416,1843384,100011.0,7400814,100011,-38.5,-2849,-2,...,-2.59325,0.0,0,0,0.0,0,0,180000.0,13320000.0,180000.0
2,100013,2038692.0,195714432,2038692,100013.0,9601248,100013,-48.5,-4656,-1,...,inf,1.0,96,1,1.0,96,1,571500.0,54864000.0,571500.0
3,100021,2594025.0,44098425,2594025,100021.0,1700357,100021,-10.0,-170,-2,...,NaN,0.0,0,0,0.0,0,0,0.0,0.0,0.0
4,100023,1499902.0,11999216,1499902,100023.0,800184,100023,-7.5,-60,-4,...,NaN,0.0,0,0,0.0,0,0,0.0,0.0,0.0

In [18]:
pos_inst_cc_merged = pos_final.merge(cc_final, on = 'SK_ID_CURR' , how='left')
pos_inst_cc_merged = pos_inst_cc_merged.merge(inst_final, on = 'SK_ID_CURR', how='left')

In [20]:
pos_inst_cc_merged.head()

,SK_ID_CURR,SK_ID_PREV_MEAN_x,SK_ID_PREV_SUM_x,SK_ID_PREV_MAX_x,MONTHS_BALANCE_MEAN_x,MONTHS_BALANCE_SUM_x,MONTHS_BALANCE_MAX_x,CNT_INSTALMENT_MEAN,CNT_INSTALMENT_SUM,CNT_INSTALMENT_MAX,...,PAYMENT_RATIO_MEAN_MAX_y,PAYMENT_RATIO_MIN_MEAN,PAYMENT_RATIO_MIN_SUM,PAYMENT_RATIO_MIN_MAX,PAYMENT_DIFF_SUM_MEAN,PAYMENT_DIFF_SUM_SUM,PAYMENT_DIFF_SUM_MAX,LATE_PAYMENTS_MEAN,LATE_PAYMENTS_SUM,LATE_PAYMENTS_MAX
0,100001,1.584045e+06,14256401,1851984,-72.555556,-653,-53,4.000000,36.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,100002,1.038818e+06,19737542,1038818,-10.000000,-190,-1,24.000000,456.0,24.0,...,1.0,1.0,8.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,100003,2.297665e+06,64334628,2636178,-43.785714,-1226,-18,10.107143,283.0,12.0,...,1.0,1.0,6.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,100004,1.564014e+06,6256056,1564014,-25.500000,-102,-24,3.750000,15.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,100005,2.495675e+06,27452425,2495675,-20.000000,-220,-15,11.700000,117.0,12.0,...,1.0,1.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
pos_inst_cc_merged.to_csv("pos_inst_cc_final.csv", index = False)