In [14]:
import pandas as pd
import numpy as np

In [15]:
prev = pd.read_csv("D:/AI/HomeCredit/Dataset/previous_application.csv")
prev.head()

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,2030495,271877,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,...,Connectivity,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0
1,2802425,108129,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,...,XNA,36.0,low_action,Cash X-Sell: low,365243.0,-134.0,916.0,365243.0,365243.0,1.0
2,2523466,122040,Cash loans,15060.735,112500.0,136444.5,NaN,112500.0,TUESDAY,11,...,XNA,12.0,high,Cash X-Sell: high,365243.0,-271.0,59.0,365243.0,365243.0,1.0
3,2819243,176158,Cash loans,47041.335,450000.0,470790.0,NaN,450000.0,MONDAY,7,...,XNA,12.0,middle,Cash X-Sell: middle,365243.0,-482.0,-152.0,-182.0,-177.0,1.0
4,1784265,202054,Cash loans,31924.395,337500.0,404055.0,NaN,337500.0,THURSDAY,9,...,XNA,24.0,high,Cash Street: high,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
prev = prev.replace(365243,np.nan)
prev.head()

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,2030495,271877.0,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,...,Connectivity,12.0,middle,POS mobile with interest,NaN,-42.0,300.0,-42.0,-37.0,0.0
1,2802425,108129.0,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,...,XNA,36.0,low_action,Cash X-Sell: low,NaN,-134.0,916.0,NaN,NaN,1.0
2,2523466,122040.0,Cash loans,15060.735,112500.0,136444.5,NaN,112500.0,TUESDAY,11,...,XNA,12.0,high,Cash X-Sell: high,NaN,-271.0,59.0,NaN,NaN,1.0
3,2819243,176158.0,Cash loans,47041.335,450000.0,470790.0,NaN,450000.0,MONDAY,7,...,XNA,12.0,middle,Cash X-Sell: middle,NaN,-482.0,-152.0,-182.0,-177.0,1.0
4,1784265,202054.0,Cash loans,31924.395,337500.0,404055.0,NaN,337500.0,THURSDAY,9,...,XNA,24.0,high,Cash Street: high,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
prev['APP_CREDIT_RATIO'] = prev['AMT_APPLICATION'] / prev['AMT_CREDIT']
prev['DOWN_PAYMENT_RATIO'] = prev['AMT_DOWN_PAYMENT'] / prev['AMT_CREDIT']
prev['CREDIT_DURATION'] = prev['DAYS_LAST_DUE'] - prev['DAYS_FIRST_DUE']
prev['DAYS_DECISION_ABS'] = abs(prev['DAYS_DECISION'])

In [18]:
prev = pd.get_dummies(prev)
prev.shape

(1670214, 168)

In [21]:
list(prev.columns)

['SK_ID_PREV',
 'SK_ID_CURR',
 'AMT_ANNUITY',
 'AMT_APPLICATION',
 'AMT_CREDIT',
 'AMT_DOWN_PAYMENT',
 'AMT_GOODS_PRICE',
 'HOUR_APPR_PROCESS_START',
 'NFLAG_LAST_APPL_IN_DAY',
 'RATE_DOWN_PAYMENT',
 'RATE_INTEREST_PRIMARY',
 'RATE_INTEREST_PRIVILEGED',
 'DAYS_DECISION',
 'SELLERPLACE_AREA',
 'CNT_PAYMENT',
 'DAYS_FIRST_DRAWING',
 'DAYS_FIRST_DUE',
 'DAYS_LAST_DUE_1ST_VERSION',
 'DAYS_LAST_DUE',
 'DAYS_TERMINATION',
 'NFLAG_INSURED_ON_APPROVAL',
 'APP_CREDIT_RATIO',
 'DOWN_PAYMENT_RATIO',
 'CREDIT_DURATION',
 'DAYS_DECISION_ABS',
 'NAME_CONTRACT_TYPE_Cash loans',
 'NAME_CONTRACT_TYPE_Consumer loans',
 'NAME_CONTRACT_TYPE_Revolving loans',
 'NAME_CONTRACT_TYPE_XNA',
 'WEEKDAY_APPR_PROCESS_START_FRIDAY',
 'WEEKDAY_APPR_PROCESS_START_MONDAY',
 'WEEKDAY_APPR_PROCESS_START_SATURDAY',
 'WEEKDAY_APPR_PROCESS_START_SUNDAY',
 'WEEKDAY_APPR_PROCESS_START_THURSDAY',
 'WEEKDAY_APPR_PROCESS_START_TUESDAY',
 'WEEKDAY_APPR_PROCESS_START_WEDNESDAY',
 'FLAG_LAST_APPL_PER_CONTRACT_N',
 'FLAG_LAST_APPL_PER_CONTRACT_Y',
 'NAME_CASH_LOAN_PURPOSE_Building a house or an annex',
 'NAME_CASH_LOAN_PURPOSE_Business development',
 'NAME_CASH_LOAN_PURPOSE_Buying a garage',
 'NAME_CASH_LOAN_PURPOSE_Buying a holiday home / land',
 'NAME_CASH_LOAN_PURPOSE_Buying a home',
 'NAME_CASH_LOAN_PURPOSE_Buying a new car',
 'NAME_CASH_LOAN_PURPOSE_Buying a used car',
 'NAME_CASH_LOAN_PURPOSE_Car repairs',
 'NAME_CASH_LOAN_PURPOSE_Education',
 'NAME_CASH_LOAN_PURPOSE_Everyday expenses',
 'NAME_CASH_LOAN_PURPOSE_Furniture',
 'NAME_CASH_LOAN_PURPOSE_Gasification / water supply',
 'NAME_CASH_LOAN_PURPOSE_Hobby',
 'NAME_CASH_LOAN_PURPOSE_Journey',
 'NAME_CASH_LOAN_PURPOSE_Medicine',
 'NAME_CASH_LOAN_PURPOSE_Money for a third person',
 'NAME_CASH_LOAN_PURPOSE_Other',
 'NAME_CASH_LOAN_PURPOSE_Payments on other loans',
 'NAME_CASH_LOAN_PURPOSE_Purchase of electronic equipment',
 'NAME_CASH_LOAN_PURPOSE_Refusal to name the goal',
 'NAME_CASH_LOAN_PURPOSE_Repairs',
 'NAME_CASH_LOAN_PURPOSE_Urgent needs',
 'NAME_CASH_LOAN_PURPOSE_Wedding / gift / holiday',
 'NAME_CASH_LOAN_PURPOSE_XAP',
 'NAME_CASH_LOAN_PURPOSE_XNA',
 'NAME_CONTRACT_STATUS_Approved',
 'NAME_CONTRACT_STATUS_Canceled',
 'NAME_CONTRACT_STATUS_Refused',
 'NAME_CONTRACT_STATUS_Unused offer',
 'NAME_PAYMENT_TYPE_Cash through the bank',
 'NAME_PAYMENT_TYPE_Cashless from the account of the employer',
 'NAME_PAYMENT_TYPE_Non-cash from your account',
 'NAME_PAYMENT_TYPE_XNA',
 'CODE_REJECT_REASON_CLIENT',
 'CODE_REJECT_REASON_HC',
 'CODE_REJECT_REASON_LIMIT',
 'CODE_REJECT_REASON_SCO',
 'CODE_REJECT_REASON_SCOFR',
 'CODE_REJECT_REASON_SYSTEM',
 'CODE_REJECT_REASON_VERIF',
 'CODE_REJECT_REASON_XAP',
 'CODE_REJECT_REASON_XNA',
 'NAME_TYPE_SUITE_Children',
 'NAME_TYPE_SUITE_Family',
 'NAME_TYPE_SUITE_Group of people',
 'NAME_TYPE_SUITE_Other_A',
 'NAME_TYPE_SUITE_Other_B',
 'NAME_TYPE_SUITE_Spouse, partner',
 'NAME_TYPE_SUITE_Unaccompanied',
 'NAME_CLIENT_TYPE_New',
 'NAME_CLIENT_TYPE_Refreshed',
 'NAME_CLIENT_TYPE_Repeater',
 'NAME_CLIENT_TYPE_XNA',
 'NAME_GOODS_CATEGORY_Additional Service',
 'NAME_GOODS_CATEGORY_Animals',
 'NAME_GOODS_CATEGORY_Audio/Video',
 'NAME_GOODS_CATEGORY_Auto Accessories',
 'NAME_GOODS_CATEGORY_Clothing and Accessories',
 'NAME_GOODS_CATEGORY_Computers',
 'NAME_GOODS_CATEGORY_Construction Materials',
 'NAME_GOODS_CATEGORY_Consumer Electronics',
 'NAME_GOODS_CATEGORY_Direct Sales',
 'NAME_GOODS_CATEGORY_Education',
 'NAME_GOODS_CATEGORY_Fitness',
 'NAME_GOODS_CATEGORY_Furniture',
 'NAME_GOODS_CATEGORY_Gardening',
 'NAME_GOODS_CATEGORY_Homewares',
 'NAME_GOODS_CATEGORY_House Construction',
 'NAME_GOODS_CATEGORY_Insurance',
 'NAME_GOODS_CATEGORY_Jewelry',
 'NAME_GOODS_CATEGORY_Medical Supplies',
 'NAME_GOODS_CATEGORY_Medicine',
 'NAME_GOODS_CATEGORY_Mobile',
 'NAME_GOODS_CATEGORY_Office Appliances',
 'NAME_GOODS_CATEGORY_Other',
 'NAME_GOODS_CATEGORY_Photo / Cinema Equipment',
 'NAME_GOODS_CATEGORY_Sport and Leisure',
 'NAME_GOODS_CATEGORY_Tourism',
 'NAME_GOODS_CATEGORY_Vehicles',
 'NAME_GOODS_CATEGORY_Weapon',
 'NAME_GOODS_CATEGORY_XNA',
 'NAME_PORTFOLIO_Cards',
 'NAME_PORTFOLIO_Cars',
 'NAME_PORTFOLIO_Cash',
 'NAME_PORTFOLIO_POS',
 'NAME_PORTFOLIO_XNA',
 'NAME_PRODUCT_TYPE_XNA',
 'NAME_PRODUCT_TYPE_walk-in',
 'NAME_PRODUCT_TYPE_x-sell',
 'CHANNEL_TYPE_AP+ (Cash loan)',
 'CHANNEL_TYPE_Car dealer',
 'CHANNEL_TYPE_Channel of corporate sales',
 'CHANNEL_TYPE_Contact center',
 'CHANNEL_TYPE_Country-wide',
 'CHANNEL_TYPE_Credit and cash offices',
 'CHANNEL_TYPE_Regional / Local',
 'CHANNEL_TYPE_Stone',
 'NAME_SELLER_INDUSTRY_Auto technology',
 'NAME_SELLER_INDUSTRY_Clothing',
 'NAME_SELLER_INDUSTRY_Connectivity',
 'NAME_SELLER_INDUSTRY_Construction',
 'NAME_SELLER_INDUSTRY_Consumer electronics',
 'NAME_SELLER_INDUSTRY_Furniture',
 'NAME_SELLER_INDUSTRY_Industry',
 'NAME_SELLER_INDUSTRY_Jewelry',
 'NAME_SELLER_INDUSTRY_MLM partners',
 'NAME_SELLER_INDUSTRY_Tourism',
 'NAME_SELLER_INDUSTRY_XNA',
 'NAME_YIELD_GROUP_XNA',
 'NAME_YIELD_GROUP_high',
 'NAME_YIELD_GROUP_low_action',
 'NAME_YIELD_GROUP_low_normal',
 'NAME_YIELD_GROUP_middle',
 'PRODUCT_COMBINATION_Card Street',
 'PRODUCT_COMBINATION_Card X-Sell',
 'PRODUCT_COMBINATION_Cash',
 'PRODUCT_COMBINATION_Cash Street: high',
 'PRODUCT_COMBINATION_Cash Street: low',
 'PRODUCT_COMBINATION_Cash Street: middle',
 'PRODUCT_COMBINATION_Cash X-Sell: high',
 'PRODUCT_COMBINATION_Cash X-Sell: low',
 'PRODUCT_COMBINATION_Cash X-Sell: middle',
 'PRODUCT_COMBINATION_POS household with interest',
 'PRODUCT_COMBINATION_POS household without interest',
 'PRODUCT_COMBINATION_POS industry with interest',
 'PRODUCT_COMBINATION_POS industry without interest',
 'PRODUCT_COMBINATION_POS mobile with interest',
 'PRODUCT_COMBINATION_POS mobile without interest',
 'PRODUCT_COMBINATION_POS other with interest',
 'PRODUCT_COMBINATION_POS others without interest']

In [22]:
approved = prev[prev['NAME_CONTRACT_STATUS_Approved'] == 1]
rejected = prev[prev['NAME_CONTRACT_STATUS_Refused'] == 1]

In [23]:
prev_agg = prev.groupby('SK_ID_CURR').agg({
    'AMT_CREDIT': ['mean', 'max'],
    'AMT_APPLICATION': ['mean'],
    'APP_CREDIT_RATIO': ['mean'],
    'DOWN_PAYMENT_RATIO': ['mean'],
    'CNT_PAYMENT': ['mean'],
    'CREDIT_DURATION': ['mean'],
    'DAYS_DECISION': ['mean', 'max'],
})

In [24]:
approved_agg = approved.groupby('SK_ID_CURR').agg({
    'AMT_CREDIT': ['mean', 'max'],
    'APP_CREDIT_RATIO': ['mean'],
})

In [25]:
rejected_agg = rejected.groupby('SK_ID_CURR').agg({
    'AMT_APPLICATION': ['mean'],
})

In [26]:
prev_counts = prev.groupby('SK_ID_CURR').agg({
    'SK_ID_PREV': 'count'
}).rename(columns={'SK_ID_PREV': 'PREV_APP_COUNT'})

In [29]:
prev_agg.head()

           AMT_CREDIT            AMT_APPLICATION APP_CREDIT_RATIO  \
                 mean        max            mean             mean
SK_ID_CURR
100001.0     23787.00    23787.0        24835.50         1.044079
100002.0    179055.00   179055.0       179055.00         1.000000
100003.0    484191.00  1035882.0       435436.50         0.949329
100004.0     20106.00    20106.0        24282.00         1.207699
100005.0     20076.75    40153.5        22308.75         1.111173

           DOWN_PAYMENT_RATIO CNT_PAYMENT CREDIT_DURATION DAYS_DECISION
                         mean        mean            mean          mean   max
SK_ID_CURR
100001.0             0.105940         8.0            90.0       -1740.0 -1740
100002.0             0.000000        24.0           540.0        -606.0  -606
100003.0             0.050585        10.0           220.0       -1305.0  -746
100004.0             0.241719         4.0            60.0        -815.0  -815
100005.0             0.111173        12.0           240.0        -536.0  -315

In [35]:
prev_agg.columns = [
    '_'.join(col).upper() if isinstance(col, tuple) else col
    for col in prev_agg.columns
]

prev_agg.reset_index(inplace=True)

prev_final = prev_agg.copy()

In [37]:
prev_final.head()

,level_0,index,SK_ID_CURR,AMT_CREDIT_MEAN,AMT_CREDIT_MAX,AMT_APPLICATION_MEAN,APP_CREDIT_RATIO_MEAN,DOWN_PAYMENT_RATIO_MEAN,CNT_PAYMENT_MEAN,CREDIT_DURATION_MEAN,DAYS_DECISION_MEAN,DAYS_DECISION_MAX
0,0,0,100001.0,23787.00,23787.0,24835.50,1.044079,0.105940,8.0,90.0,-1740.0,-1740
1,1,1,100002.0,179055.00,179055.0,179055.00,1.000000,0.000000,24.0,540.0,-606.0,-606
2,2,2,100003.0,484191.00,1035882.0,435436.50,0.949329,0.050585,10.0,220.0,-1305.0,-746
3,3,3,100004.0,20106.00,20106.0,24282.00,1.207699,0.241719,4.0,60.0,-815.0,-815
4,4,4,100005.0,20076.75,40153.5,22308.75,1.111173,0.111173,12.0,240.0,-536.0,-315

In [39]:
approved_agg.columns = [
    '_'.join(col).upper() if isinstance(col, tuple) else col
    for col in approved_agg.columns
]
approved_agg.reset_index(inplace=True)

In [40]:
rejected_agg.columns = [
    '_'.join(col).upper() if isinstance(col, tuple) else col
    for col in rejected_agg.columns
]
rejected_agg.reset_index(inplace=True)

In [41]:
prev_final = prev_final.merge(approved_agg, on='SK_ID_CURR', how='left')
prev_final = prev_final.merge(rejected_agg, on='SK_ID_CURR', how='left')
prev_final = prev_final.merge(prev_counts, on='SK_ID_CURR', how='left')

In [42]:
prev_final.head()

,level_0,index,SK_ID_CURR,AMT_CREDIT_MEAN_x,AMT_CREDIT_MAX_x,AMT_APPLICATION_MEAN_x,APP_CREDIT_RATIO_MEAN_x,DOWN_PAYMENT_RATIO_MEAN,CNT_PAYMENT_MEAN,CREDIT_DURATION_MEAN,DAYS_DECISION_MEAN,DAYS_DECISION_MAX,AMT_CREDIT_MEAN_y,AMT_CREDIT_MAX_y,APP_CREDIT_RATIO_MEAN_y,AMT_APPLICATION_MEAN_y,PREV_APP_COUNT
0,0,0,100001.0,23787.00,23787.0,24835.50,1.044079,0.105940,8.0,90.0,-1740.0,-1740,23787.0,23787.0,1.044079,NaN,1
1,1,1,100002.0,179055.00,179055.0,179055.00,1.000000,0.000000,24.0,540.0,-606.0,-606,179055.0,179055.0,1.000000,NaN,1
2,2,2,100003.0,484191.00,1035882.0,435436.50,0.949329,0.050585,10.0,220.0,-1305.0,-746,484191.0,1035882.0,0.949329,NaN,3
3,3,3,100004.0,20106.00,20106.0,24282.00,1.207699,0.241719,4.0,60.0,-815.0,-815,20106.0,20106.0,1.207699,NaN,1
4,4,4,100005.0,20076.75,40153.5,22308.75,1.111173,0.111173,12.0,240.0,-536.0,-315,40153.5,40153.5,1.111173,NaN,2

In [44]:
prev_final.to_csv("D:/AI/HomeCredit/Processed_data/prev_final.csv", index=False)